# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Description of what the lane does"

  lane :build do
    app_store_connect_api_key
    match
    project = "MyWallet.xcodeproj"
    gym(
      project: project,
      silent: true,                             
      clean: true,                             
      export_method: "app-store",
      export_options: {
        provisioningProfiles: { 
          "gr.marseltzatzo.MyWallet" => ENV["sigh_gr.marseltzatzo.MyWallet_appstore_profile-name"]
        }
      },
      output_directory: '.archives',
      output_name: 'MyWallet-AppStore.ipa'
    )
    pilot(
      app_platform: 'ios',
      ipa: ".archives/MyWallet-AppStore.ipa",
      skip_submission: true,
      skip_waiting_for_build_processing: true,
      reject_build_waiting_for_review: true
    )
  end

end
